<?php
/**
 * Autoplug "FrontendAdmin" to allow markdown with frontend features
 *
 * @category   Autoplugs
 * @package    MarkupMarkdown
 * @since      3.15.0
 */

namespace MarkupMarkdown\AutoPlugs;

defined( 'ABSPATH' ) || exit;


/**
 * This class adds a few hooks to allow the use of markdown with the forms generated by FrontEnd Admin
 */
final class FrontendAdmin {


	/**
	 * Storing FrontEnd Admin related data
	 *
	 * @var array
	 */
	private $env = array();


	/**
	 * Initialize. Active by default
	 */
	public function __construct() {
		define( 'MARKUP_MARKDOWN_FRONTENDADMIN_PLUG', true );
		$this->env['version'] = '1.0.2';
		if ( ! is_admin() ) :
			add_action( 'wp_enqueue_scripts', array( $this, 'markup_markdown_queues' ) );
		else :
			add_action( 'init', array( $this, 'allow_frontend_admin' ) );
		endif;
	}


	/**
	 * Check the current template in used and enqueue the markdown editor assets if need be
	 *
	 * @return boolean TRUE in case a FrontEnd Admin shortcode was triggered, FALSE otherwise
	 */
	public function markup_markdown_queues() {
		if ( ! is_singular() ) :
			return false;
		endif;
		global $post;
		if ( ! isset( $post ) || ! isset( $post->post_content ) || ! preg_match( '#\[frontend_admin#', $post->post_content ) ) :
			return false;
		endif;
		add_filter( 'markup_markdown_frontend_enabled', '__return_true' );
		$base_dir = markup_markdown()->plugin_uri . 'assets/acf-frontend-form-element/';
		$ver      = $this->env['version'];
		// Register and enqueue the plug's script.
		wp_register_script( 'markup_markdown__acf_frontendform', $base_dir . 'js/field.min.js', array( 'jquery' ), $ver, true );
		wp_enqueue_script( 'markup_markdown__acf_frontendform' );
		// Register and enqueue the plug's stylesheet.
		wp_register_style( 'markup_markdown__acf_frontendform', $base_dir . 'css/field.min.css', array(), $ver );
		wp_enqueue_style( 'markup_markdown__acf_frontendform' );
		// Hook frontend_admin/forms/before_render.
		// Hook frontend_admin/after_form.
		return true;
	}


	/**
	 * Filter to allow block editors with the form setup screen
	 *
	 * @access public
	 * @since 3.17.1
	 *
	 * @return void
	 */
	public function allow_frontend_admin() {
		remove_post_type_support( 'admin_form', 'markup_markdown' );
	}
}
